name: "tiny_forms"
description: "TinyForms is a minimalistic Flutter package for building simple and lightweight forms with easy customization and validation."
version: "0.1.0+6"
homepage: "https://github.com/sheeroo/tiny_forms"

environment: 
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies: 
  equatable: "^2.0.5"
  flutter: 
    sdk: "flutter"

  flutter_bloc: "^8.1.2"

dev_dependencies: 
  flutter_test: 
    sdk: "flutter"

  mocktail: "^0.3.0"
  very_good_analysis: "^3.1.0"